### ISSUE TITLE
<br> gebruik

### ISSUE THREAD

**Issue by MokhtarAkle** [ArexanK/the-startup-responsive-interactieve-website#10]
https://github.com/ArexanK/the-startup-responsive-interactieve-website/blob/5a8767529891ee0539d5985fdd546d92abbcbcca/index.html#L73

Kijk uit met <br> gebruiken als dit niet nodig is. Om je container te stylen kan je beter gebruik maken van CSS, bijvoorbeeld met flexbox

**Comment by ArexanK** [comment]
aangepast
