### ISSUE TITLE
Max-width paragrafen

### ISSUE THREAD

**Issue by Stefan-Espant** [ArexanK/the-startup-responsive-interactieve-website#14]
Om paragrafen leesbaar te maken, geef ze een maximale lengte om tussen de 11-13 woorden uit te komen.
11-13 woorden staat gelijk aan 30em ongeveer.

Hoe je dit in css doet gaat alsvolgt:

```css
p {
 max-width: 30em;
}

```

**Comment by ArexanK** [comment]
goeie, thanks ik heb het aangepast
