### ISSUE TITLE
Favicon ontbreekt nog

### ISSUE THREAD

**Issue by Stefan-Espant** [ArexanK/the-startup-responsive-interactieve-website#18]
Om je website nog meer te customizen, kan je een favicon gebruiken om zo goed op te vallen in je browser.
Dit kan je in `html` gewoon implementeren. Specifiek in je `head`

Voorbeeld:
```html
<link rel="icon" type="image/png" href="./assets/favicon.png">
```

**Comment by ArexanK** [comment]
thanks
